### ISSUE TITLE
Support publishing files excluded at top level

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno_config#36]
Not sure if this is handled, but should there be a way to opt-out of a top level exclude? Should this work?

```json
{
  "publish": {
    "include": "./dist"
  },
  "exclude": ["./dist"]
}
```

Someone may want to exclude the dist folder from the lsp, fmt, lint, etc, but then include it for publishing because it contains a build of the package.

_Originally posted by @dsherret in https://github.com/denoland/deno_config/pull/34#discussion_r1463726264_

**Comment by dsherret** [comment]
Closed by https://github.com/denoland/deno_config/pull/44

Solution is to opt out of an exclude at a more specific level:

```
{
  "publish": {
    "exclude": [
      "!./dist"
    ]
  },
  "exclude": ["./dist"]
}
```
